name: Update README

on:
  push:
    branches:
    - main
    paths:
     - 'data/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Generate
      run: |
        make generator
    - name: Update README
      run: |
        git config user.name "AutoUpdater"
        git config user.email ${{ env.EMAIL }}
        git add README.md
        git commit -m "Update README"
        git push
    
